### PR TITLE
Move google cloud CI machine to us-east4

### PR DESCRIPTION
**Pull request by rn**
Docker hub is located mostly in US east. Moving CI closer to it
should reduce the network latency and hopefully improve the
execution times of running tests (which pull a lot of images
from hub)

relates to https://github.com/linuxkit/linuxkit/issues/2106

Signed-off-by: Rolf Neugebauer <rolf.neugebauer@docker.com>

### CODE REVIEW

**Comment by rn** [comment]
ping @talex5 could we deploy this and see if it changes anything?

**Comment by talex5** [comment]
Do you want to use a faster machine type too?

**Comment by talex5** [comment]
We merged the CPU type and timing PRs first. Do we still want this? @dave-tucker had some questions:

https://dockercommunity.slack.com/archives/C51K0GDU7/p1498656968614182

**Comment by rn** [comment]
it's unclear if we are limited on network latency for the test. This is trivial enough to replicate (plus there are some other issues), so closing for now

**Pull request closed without merging**
