### PR TITLE
Save contents of test/_results after building

### PR DESCRIPTION
**Pull request by talex5**
Note: doesn't work as there don't appear to be any test results generated.

### CODE REVIEW

**Comment by rn** [comment]
I don't understand the comment of it not working because no results are being generated. If I run locally test results are in `./test/_results/<UUID>/`

**Comment by talex5** [comment]
Is this with `make ci-pr`?

**Comment by rn** [comment]
yes, just tested locally

**Comment by talex5** [comment]
Ah, yes, I was testing an out-of-date commit.

**Comment by rn** [comment]
can you enable this?

**Comment by talex5** [comment]
It is enabled, but nothing has finished building yet so I don't know if it works...

**Comment by talex5** [comment]
Seems to be working:
- branch: https://github.com/linuxkit/linuxkit-logs/tree/linuxkit-build-of-9fd743a28fd363b9ec0bdbd8800932e3026f1eba-default-ci
- PR: https://github.com/linuxkit/linuxkit-logs/tree/linuxkit-build-of-6c4722d4a92f71e1d76c65083141f481a58a96b3-default-ci-pr/value/da9b09a0-3781-4c50-82d2-c4181c6307c8

**Pull request merged**
