### PR TITLE
lk: artifacts have moved to a subdirectory

### PR DESCRIPTION
**Pull request by talex5**
@dave-tucker is this what you were after?

Note: to test locally, just change https://github.com/linuxkit/linuxkit-ci/blob/master/src/linuxkit_build.ml#L234 to match on `_`.

### CODE REVIEW

**Comment by dave-tucker** [comment]
Yes it is.
Will the GCP test will also need to know that the path where it looks for `test.img.tar.gz` should now be in the artifacts dir?

**Comment by talex5** [comment]
No, because it gets the image from the cache and that hasn't changed.

I've deployed this version now, if you want to make (or rebuild) a PR to check.

**Comment by dave-tucker** [comment]
Rebasing my test cleanup PR now...

**Comment by dave-tucker** [comment]
LGTM!

**Comment by dave-tucker** [comment]
Thanks @talex5 👍

**Pull request merged**
